#!/usr/bin/perl
###########################################
# release -- Release this module
use warnings;
use strict;

    # Available at http://perlmeister.com/scripts
use ModDevUtils;

ModDevUtils::release() or exit 0;
